pipeline {
    agent {
        docker {
            image 'mlungwsr/ubuntu-awscli'
            args '-u 0'
        }
    }

    stages {
        stage ('Connection') {
            steps {
                sh "aws configure set aws_access_key_id AKIA4GQAF5VVH5SMF4KR"
                sh "aws configure set aws_secret_access_key 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"
                sh "aws configure set profile.dmc-cloudformation-user.region us-east-2"
                sh "aws configure set region us-east-2"
            }
        }
        stage('Test'){
            steps {
                sh 'aws --version'
                sh 'aws s3 ls'
            }
        }
        stage ('Deploy') {
            steps {
                sh 'aws cloudformation create-stack  --stack-name mystack-dmc-prueba ' +
                        '--template-body file://cloudformation/WebServerSecurityGroup'
//                        '\\\n' +
//                        '  --parameters ParameterKey=Parm1,ParameterValue=test1 ParameterKey=Parm2,ParameterValue=test2'
            }
        }
    }
}
