pipeline {
    agent any
    stages {
        stage ('Repository') {
            steps {
                checkout scm
            }
        }
        stage ('Test & Build') {
            steps {
                sh 'echo test_build building'
            }
        }
        stage ('Deploy') {
            steps {
                sh 'echo deploying python app'
            }
        }
    }
}
