pipeline {
    agent any
    stages {
        stage ('1 pasoRepository') {
            steps {
                checkout scm
            }
        }
        stage ('2 pasoTest & Build') {
            steps {
                sh 'echo test_build building'
            }
        }
        stage ('Deploy') {
            steps {
                sh 'echo deploying python app'
            }
        }
    }
}
