pipeline {
  agent any
  stages {

    stage ("Repo") {
      steps {
        checkout scm
      }
    }

    stage ("Build") {
      steps {
        // TODO mejorar con script
      }
    }

    stage ("Test") {
      steps {

      }
    }

    stage ("Upload") {
      steps {
          // TODO: mejorar con script

        }
      }
    }

  post {
    always {
    }
  }

}
